name: Main Repository Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update_main_branch

jobs:
  build_desdeo_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add more steps here based on your build and test requirements for the DESDEO framework

      - name: Update Main Branch
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git checkout main
          git merge "${{ github.head_ref }}"
          git push origin main
