name: Problem Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  build_desdeo_and_test_problem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build DESDEO framework
        run: |
          # Build the DESDEO framework from the main repository
          # Replace the build steps with the appropriate commands for building the framework

      # Add more steps here based on your build requirements for the DESDEO framework

      - name: Return to Problem Repository
        run: |
          cd ../desdeo-problem

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run problem tests
        run: |
          # Run the tests for the problem repository
          # Replace this command with the appropriate test command for the problem repository
